import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Hacker News Logo Hacker News' }).click();
  await page.getByRole('link', { name: 'Go to next page' }).first().click();
  await page.getByRole('link', { name: '24' }).first().click();
  await page.getByRole('link', { name: '1' }).first().click();
  await page.getByRole('link', { name: '2', exact: true }).first().click();
  await page.getByRole('link', { name: 'Go to previous page' }).first().click();
  await page.getByRole('button', { name: 'New' }).click();
  await page.locator('textarea[name="text"]').click();
  await page.getByRole('button', { name: 'Past' }).click();
  await page.getByRole('button', { name: 'Ask' }).click();
  await page.getByRole('button', { name: 'Show' }).click();
  await page.getByRole('link', { name: 'Jobs', exact: true }).getByRole('button').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Login', exact: true }).click();
  await page.getByRole('textbox', { name: 'USERNAME' }).click();
  await page.getByRole('textbox', { name: 'PASSWORD' }).click();
  await page.getByRole('button', { name: 'LOGIN', exact: true }).click();
  await page.getByRole('button', { name: 'You need an account? Sign up' }).click();
  await page.getByRole('textbox', { name: 'USERNAME' }).click();
  await page.getByRole('textbox', { name: 'PASSWORD' }).click();
  await page.getByRole('button', { name: 'Sign up' }).click();
  await page.getByRole('button', { name: 'You already have an account?' }).click();
  await page.getByRole('button', { name: 'Forgot your password?' }).click();
  await page.getByRole('textbox', { name: 'USERNAME' }).click();
  await page.getByRole('button', { name: 'Send reset email' }).click();
  await page.getByRole('link', { name: 'Hacker News Logo Hacker News' }).click();
  await page.getByRole('link', { name: 'Guidelines' }).click();
  await page.getByRole('link', { name: 'FAQ' }).click();
  await page.getByRole('button', { name: 'Guidelines' }).click();
  await page.getByRole('link', { name: 'FAQ' }).click();
  await page.getByRole('button', { name: 'Format guide' }).click();
  await page.locator('body').click();
  await page.getByRole('button', { name: 'Use the poll submission form' }).click();
  await page.getByRole('link', { name: 'Lists' }).click();
  await page.getByRole('link', { name: 'API' }).click();
  await page.getByRole('link', { name: 'Security' }).click();
  await page.getByRole('link', { name: 'Legal' }).click();
  await page.goto('http://localhost:3000/footer/security');
  await page.getByRole('link', { name: 'Apply to YC' }).click();
  await page.getByRole('link', { name: 'Contact' }).click();
});