import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/page";
import Footer from "@/components/footer/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logo/favicon.ico" />
      </head>
      <body>
        <Navbar />
        <main>{children}</main>
        <footer><Footer /></footer>
      </body>
    </html>
  );
}
